package com.example.localization

data class AppStrings(
    // Bottom Dock Navigation
    val navHome: String,
    val navCalendar: String,
    val navTasks: String,
    val navInsights: String,
    val navMore: String,
    val navCreate: String,

    // Header & System Bar
    val liveBioSync: String,
    val syncedJustNow: String,
    val focusPill: String,
    val focusActivePill: String,
    val searchPlaceholder: String,
    val notificationsTooltip: String,
    val notificationsMutedTooltip: String,
    val aiCopilotTooltip: String,

    // Focus Mode Screen
    val focusModeHeader: String,
    val mutedBadge: String,
    val mutedSubtitle: String,
    val exitFocusButton: String,
    val activeFocusTaskQueue: String,
    val subtasksChecklist: String,
    val markTaskComplete: String,
    val pomodoroFocusTitle: String,
    val timerStart: String,
    val timerPause: String,
    val focusSanctuaryClearTitle: String,
    val focusSanctuaryClearSubtitle: String,

    // Command Center & Settings
    val commandCenterTitle: String,
    val commandCenterSubtitle: String,
    val languageSectionTitle: String,
    val languageCardSubtitle: String,
    val selectLanguageButton: String,
    val searchLanguagePlaceholder: String,
    val themeSectionTitle: String,
    val darkModeTitle: String,
    val darkModeActiveSubtitle: String,
    val lightModeActiveSubtitle: String,
    val themeLight: String,
    val themeDark: String,
    val themeAuto: String,
    val calendarSyncTitle: String,
    val calendarSyncActiveSubtitle: String,
    val calendarSyncDisabledSubtitle: String,

    // Core Engines & Modules
    val coreIntelligenceHeader: String,
    val automationsTitle: String,
    val automationsSubtitle: String,
    val aiCopilotTitle: String,
    val aiCopilotSubtitle: String,
    val dailyBriefingTitle: String,
    val dailyBriefingSubtitle: String,

    // Workspaces
    val productivityWorkspacesHeader: String,
    val meetingsTitle: String,
    val meetingsSubtitle: String,
    val meetingMinutesTitle: String,
    val meetingMinutesSubtitle: String,
    val pomodoroSanctuaryTitle: String,
    val pomodoroSanctuarySubtitle: String,
    val notesTitle: String,
    val notesSubtitle: String,

    // Habits & Goals
    val habitsGoalsWellnessHeader: String,
    val habitsTitle: String,
    val habitsSubtitle: String,
    val goalsTitle: String,
    val goalsSubtitle: String,
    val remindersTitle: String,
    val remindersSubtitle: String,

    // Finance & Commerce
    val financeBillsCommerceHeader: String,
    val financeDashboardTitle: String,
    val financeDashboardSubtitle: String,
    val subscriptionsTitle: String,
    val subscriptionsSubtitle: String,
    val shoppingListsTitle: String,
    val shoppingListsSubtitle: String,

    // Travel & Security
    val travelSecurityHeader: String,
    val travelItineraryTitle: String,
    val travelItinerarySubtitle: String,
    val secureVaultTitle: String,
    val secureVaultSubtitle: String,
    val contactsTitle: String,
    val contactsSubtitle: String,

    // Financial Health Arc Gauge
    val financialHealthTitle: String,
    val spendingVelocitySubtitle: String,
    val budgetTargetLimitButton: String,
    val velocityDialTab: String,
    val runwayLimitTab: String,
    val statusSafe: String,
    val statusSustainable: String,
    val statusCaution: String,
    val statusDanger: String,
    val currentSpendOfLimit: String,

    // General Actions & Labels
    val priorityHigh: String,
    val priorityMedium: String,
    val priorityLow: String,
    val autoSortByPriority: String,
    val actionSave: String,
    val actionCancel: String,
    val actionClose: String,
    val actionDone: String,
    val actionEdit: String,
    val actionDelete: String,
    val today: String,
    val upcoming: String
)

object Translations {
    val english = AppStrings(
        navHome = "Home",
        navCalendar = "Calendar",
        navTasks = "Tasks",
        navInsights = "Insights",
        navMore = "More",
        navCreate = "Create",

        liveBioSync = "LIVE BIO-SYNC",
        syncedJustNow = "Synced just now",
        focusPill = "Focus",
        focusActivePill = "Focus ON",
        searchPlaceholder = "Search tasks, events, bills...",
        notificationsTooltip = "All systems synced: Calendar, Health, Tasks & Budget",
        notificationsMutedTooltip = "🤫 Notifications muted: 12 non-urgent alerts silenced in Focus Mode",
        aiCopilotTooltip = "DayMeet AI Copilot",

        focusModeHeader = "FOCUS MODE ACTIVE",
        mutedBadge = "MUTED",
        mutedSubtitle = "12 non-urgent alerts muted (Slack, email & reminders)",
        exitFocusButton = "Exit",
        activeFocusTaskQueue = "ACTIVE FOCUS TASK QUEUE",
        subtasksChecklist = "SUBTASKS CHECKLIST",
        markTaskComplete = "Mark Task Complete",
        pomodoroFocusTitle = "Deep Focus Pomodoro",
        timerStart = "Start",
        timerPause = "Pause",
        focusSanctuaryClearTitle = "Focus Sanctuary Clear!",
        focusSanctuaryClearSubtitle = "You have completed all pending tasks in your queue. Take a well-deserved break or return to standard dashboard view.",

        commandCenterTitle = "Command Center",
        commandCenterSubtitle = "All modules, connected automations, finance, health, and personal tools",
        languageSectionTitle = "LANGUAGE & LOCALIZATION",
        languageCardSubtitle = "Dynamic multilingual engine • Instant app-wide language switching",
        selectLanguageButton = "Change Language",
        searchLanguagePlaceholder = "Search language or country...",
        themeSectionTitle = "SYSTEM APPEARANCE & TAILWIND THEME",
        darkModeTitle = "System-Wide Dark Mode",
        darkModeActiveSubtitle = "Tailwind Slate-900 canvas active • High-contrast OLED",
        lightModeActiveSubtitle = "Tailwind Light canvas active • High-clarity neutral theme",
        themeLight = "☀️ Light",
        themeDark = "🌙 Dark (Slate)",
        themeAuto = "⚙️ Auto",
        calendarSyncTitle = "Sync Device Calendar Notifications",
        calendarSyncActiveSubtitle = "Active: DayMeet alerts mirrored with local system calendar",
        calendarSyncDisabledSubtitle = "Disabled: Only internal DayMeet alert engine will notify you",

        coreIntelligenceHeader = "CORE INTELLIGENCE & ENGINES",
        automationsTitle = "Automations & Rules Engine",
        automationsSubtitle = "When → If → Then automated daily workflows",
        aiCopilotTitle = "DayMeet AI Copilot",
        aiCopilotSubtitle = "Natural language schedule restructuring & insights",
        dailyBriefingTitle = "Morning & Evening Briefings",
        dailyBriefingSubtitle = "High-level summary of day's commitments & vitals",

        productivityWorkspacesHeader = "PRODUCTIVITY & WORKSPACES",
        meetingsTitle = "Meetings & Video Conferences",
        meetingsSubtitle = "Sync Google Meet, Zoom, MS Teams & attendees",
        meetingMinutesTitle = "Meeting Minutes & Action Items",
        meetingMinutesSubtitle = "Convert speaker takeaways into assigned tasks",
        pomodoroSanctuaryTitle = "Deep Focus & Pomodoro Sanctuary",
        pomodoroSanctuarySubtitle = "DND mode with ambient sounds & auto-responder",
        notesTitle = "Notes, Docs & Knowledge Base",
        notesSubtitle = "Quick capture, voice notes & tags",

        habitsGoalsWellnessHeader = "HABITS, GOALS & WELLNESS",
        habitsTitle = "Habits & Routine Streaks",
        habitsSubtitle = "Track daily habits and morning routines",
        goalsTitle = "Goals & Milestones",
        goalsSubtitle = "Financial, fitness & career target tracking",
        remindersTitle = "Smart Reminders & Location Alerts",
        remindersSubtitle = "Location, time & cross-module triggers",

        financeBillsCommerceHeader = "FINANCE, BILLS & COMMERCE",
        financeDashboardTitle = "Finance Dashboard & Ledger",
        financeDashboardSubtitle = "Daily spending, monthly budget & auto-categorization",
        subscriptionsTitle = "Subscriptions & Recurring Bills",
        subscriptionsSubtitle = "Electricity, Fiber, Netflix & Figma tracker",
        shoppingListsTitle = "Shopping & Grocery Lists",
        shoppingListsSubtitle = "Auto-budget estimation & aisle checkboxes",

        travelSecurityHeader = "TRAVEL, SECURITY & COMMUNICATION",
        travelItineraryTitle = "Travel Itinerary & Trips",
        travelItinerarySubtitle = "Flights, hotel reservations & packing list",
        secureVaultTitle = "Secure Document Vault",
        secureVaultSubtitle = "Passport, insurance, lease with on-device encryption",
        contactsTitle = "Contacts & Scheduled Messages",
        contactsSubtitle = "CRM directory, birthday concierge & automated Slack/WhatsApp",

        financialHealthTitle = "Financial Health",
        spendingVelocitySubtitle = "Spending Velocity",
        budgetTargetLimitButton = "Limit",
        velocityDialTab = "Velocity Dial",
        runwayLimitTab = "Runway & Limit",
        statusSafe = "Safe",
        statusSustainable = "Sustainable",
        statusCaution = "Caution",
        statusDanger = "Danger",
        currentSpendOfLimit = "of limit",

        priorityHigh = "High",
        priorityMedium = "Medium",
        priorityLow = "Low",
        autoSortByPriority = "Auto-sort by Priority",
        actionSave = "Save",
        actionCancel = "Cancel",
        actionClose = "Close",
        actionDone = "Done",
        actionEdit = "Edit",
        actionDelete = "Delete",
        today = "Today",
        upcoming = "Upcoming"
    )

    val spanish = AppStrings(
        navHome = "Inicio",
        navCalendar = "Calendario",
        navTasks = "Tareas",
        navInsights = "Análisis",
        navMore = "Más",
        navCreate = "Crear",

        liveBioSync = "BIO-SINCRONIZACIÓN",
        syncedJustNow = "Sincronizado ahora",
        focusPill = "Enfoque",
        focusActivePill = "Enfoque ACT",
        searchPlaceholder = "Buscar tareas, eventos, gastos...",
        notificationsTooltip = "Sistemas sincronizados: Calendario, Salud, Tareas y Presupuesto",
        notificationsMutedTooltip = "🤫 Notificaciones silenciadas: 12 alertas pausadas en Modo Enfoque",
        aiCopilotTooltip = "Copiloto de IA DayMeet",

        focusModeHeader = "MODO ENFOQUE ACTIVO",
        mutedBadge = "SILENCIADO",
        mutedSubtitle = "12 alertas no urgentes silenciadas (Slack, correo y avisos)",
        exitFocusButton = "Salir",
        activeFocusTaskQueue = "COLA DE TAREAS EN ENFOQUE",
        subtasksChecklist = "LISTA DE SUBTAREAS",
        markTaskComplete = "Marcar Tarea Completada",
        pomodoroFocusTitle = "Pomodoro de Enfoque Profundo",
        timerStart = "Iniciar",
        timerPause = "Pausar",
        focusSanctuaryClearTitle = "¡Santuario de Enfoque Completado!",
        focusSanctuaryClearSubtitle = "Has completado todas las tareas pendientes de la cola. Tómate un merecido descanso o regresa al panel.",

        commandCenterTitle = "Centro de Control",
        commandCenterSubtitle = "Módulos, automatizaciones, finanzas, salud y herramientas personales",
        languageSectionTitle = "IDIOMA Y LOCALIZACIÓN",
        languageCardSubtitle = "Motor dinámico multilingüe • Cambio instantáneo en toda la app",
        selectLanguageButton = "Cambiar Idioma",
        searchLanguagePlaceholder = "Buscar idioma o país...",
        themeSectionTitle = "APARIENCIA DEL SISTEMA Y TEMA",
        darkModeTitle = "Modo Oscuro Global",
        darkModeActiveSubtitle = "Lienzo Tailwind Slate-900 activo • Alto contraste OLED",
        lightModeActiveSubtitle = "Lienzo Tailwind Claro activo • Tema neutro de alta claridad",
        themeLight = "☀️ Claro",
        themeDark = "🌙 Oscuro (Slate)",
        themeAuto = "⚙️ Automático",
        calendarSyncTitle = "Sincronizar Alertas del Calendario",
        calendarSyncActiveSubtitle = "Activo: Las alertas de DayMeet se reflejan en el calendario local",
        calendarSyncDisabledSubtitle = "Desactivado: Solo las alertas internas de DayMeet notificarán",

        coreIntelligenceHeader = "INTELIGENCIA Y MOTORES PRINCIPALES",
        automationsTitle = "Motor de Reglas y Automatizaciones",
        automationsSubtitle = "Flujos diarios automatizados Cuando → Si → Entonces",
        aiCopilotTitle = "Copiloto de IA DayMeet",
        aiCopilotSubtitle = "Reestructuración de agenda en lenguaje natural",
        dailyBriefingTitle = "Resumen Matutino y Nocturno",
        dailyBriefingSubtitle = "Resumen de alto nivel de compromisos y constantes",

        productivityWorkspacesHeader = "PRODUCTIVIDAD Y ESPACIOS DE TRABAJO",
        meetingsTitle = "Reuniones y Videoconferencias",
        meetingsSubtitle = "Sincroniza Google Meet, Zoom, MS Teams y asistentes",
        meetingMinutesTitle = "Minutas y Puntos de Acción",
        meetingMinutesSubtitle = "Convierte puntos clave en tareas asignadas",
        pomodoroSanctuaryTitle = "Santuario de Concentración Pomodoro",
        pomodoroSanctuarySubtitle = "Modo No Molestar con sonidos ambientales",
        notesTitle = "Notas, Documentos y Conocimiento",
        notesSubtitle = "Captura rápida, notas de voz y etiquetas",

        habitsGoalsWellnessHeader = "HÁBITOS, METAS Y BIENESTAR",
        habitsTitle = "Hábitos y Rachas de Rutina",
        habitsSubtitle = "Seguimiento de hábitos y rutinas matutinas",
        goalsTitle = "Metas e Hitos",
        goalsSubtitle = "Seguimiento financiero, físico y profesional",
        remindersTitle = "Recordatorios Inteligentes",
        remindersSubtitle = "Disparadores por ubicación, hora y módulos",

        financeBillsCommerceHeader = "FINANZAS, CUENTAS Y COMERCIO",
        financeDashboardTitle = "Panel Financiero y Libro Mayor",
        financeDashboardSubtitle = "Gasto diario, presupuesto mensual y categorización",
        subscriptionsTitle = "Suscripciones y Facturas Periódicas",
        subscriptionsSubtitle = "Luz, Fibra, Netflix y seguimiento de servicios",
        shoppingListsTitle = "Listas de Compras y Supermercado",
        shoppingListsSubtitle = "Estimación automática de presupuesto y pasillos",

        travelSecurityHeader = "VIAJES, SEGURIDAD Y CONTACTOS",
        travelItineraryTitle = "Itinerario de Viaje y Rutas",
        travelItinerarySubtitle = "Vuelos, hoteles y lista de equipaje",
        secureVaultTitle = "Bóveda Segura de Documentos",
        secureVaultSubtitle = "Pasaporte, seguro y contratos cifrados localmente",
        contactsTitle = "Contactos y Mensajes Programados",
        contactsSubtitle = "Directorio CRM y avisos automatizados",

        financialHealthTitle = "Salud Financiera",
        spendingVelocitySubtitle = "Velocidad de Gasto",
        budgetTargetLimitButton = "Límite",
        velocityDialTab = "Dial de Velocidad",
        runwayLimitTab = "Margen y Límite",
        statusSafe = "Seguro",
        statusSustainable = "Sostenible",
        statusCaution = "Precaución",
        statusDanger = "Peligro",
        currentSpendOfLimit = "del límite",

        priorityHigh = "Alta",
        priorityMedium = "Media",
        priorityLow = "Baja",
        autoSortByPriority = "Ordenar por Prioridad",
        actionSave = "Guardar",
        actionCancel = "Cancelar",
        actionClose = "Cerrar",
        actionDone = "Listo",
        actionEdit = "Editar",
        actionDelete = "Eliminar",
        today = "Hoy",
        upcoming = "Próximos"
    )

    val french = AppStrings(
        navHome = "Accueil",
        navCalendar = "Calendrier",
        navTasks = "Tâches",
        navInsights = "Analyses",
        navMore = "Plus",
        navCreate = "Créer",

        liveBioSync = "BIO-SYNCHRO DIRECT",
        syncedJustNow = "Synchronisé à l'instant",
        focusPill = "Focus",
        focusActivePill = "Focus ACTIF",
        searchPlaceholder = "Rechercher tâches, événements...",
        notificationsTooltip = "Systèmes synchronisés: Calendrier, Santé, Tâches et Budget",
        notificationsMutedTooltip = "🤫 Notifications en sourdine: 12 alertes silencieuses en mode Focus",
        aiCopilotTooltip = "Copilote IA DayMeet",

        focusModeHeader = "MODE FOCUS ACTIF",
        mutedBadge = "EN SOURDINE",
        mutedSubtitle = "12 alertes non urgentes réduites au silence (Slack, courriel)",
        exitFocusButton = "Quitter",
        activeFocusTaskQueue = "FILE DE TÂCHES FOCUS",
        subtasksChecklist = "LISTE DES SOUS-TÂCHES",
        markTaskComplete = "Marquer comme Terminée",
        pomodoroFocusTitle = "Pomodoro Concentration Profonde",
        timerStart = "Démarrer",
        timerPause = "Pause",
        focusSanctuaryClearTitle = "Sanctuaire Focus Terminé!",
        focusSanctuaryClearSubtitle = "Toutes les tâches en attente sont accomplies. Prenez une pause bien méritée.",

        commandCenterTitle = "Centre de Contrôle",
        commandCenterSubtitle = "Modules, automatisations, finances, santé et outils personnels",
        languageSectionTitle = "LANGUE ET LOCALISATION",
        languageCardSubtitle = "Moteur multilingue dynamique • Changement instantané dans toute l'application",
        selectLanguageButton = "Changer de Langue",
        searchLanguagePlaceholder = "Rechercher langue ou pays...",
        themeSectionTitle = "APPARENCE DU SYSTÈME ET THÈME",
        darkModeTitle = "Mode Sombre Global",
        darkModeActiveSubtitle = "Arrière-plan Tailwind Slate-900 actif • OLED haut contraste",
        lightModeActiveSubtitle = "Arrière-plan Tailwind Clair actif • Clarté neutre",
        themeLight = "☀️ Clair",
        themeDark = "🌙 Sombre (Slate)",
        themeAuto = "⚙️ Automatique",
        calendarSyncTitle = "Synchroniser les Alertes Calendrier",
        calendarSyncActiveSubtitle = "Actif: Alertes DayMeet répliquées sur le calendrier local",
        calendarSyncDisabledSubtitle = "Désactivé: Seules les alertes internes DayMeet sonneront",

        coreIntelligenceHeader = "INTELLIGENCE CENTRALE ET MOTEURS",
        automationsTitle = "Moteur d'Automatisations et Règles",
        automationsSubtitle = "Flux quotidiens Quand → Si → Alors",
        aiCopilotTitle = "Copilote IA DayMeet",
        aiCopilotSubtitle = "Restructuration d'emploi du temps en langage naturel",
        dailyBriefingTitle = "Briefings Matin et Soir",
        dailyBriefingSubtitle = "Vue synthétique des engagements du jour",

        productivityWorkspacesHeader = "PRODUCTIVITÉ ET ESPACES DE TRAVAIL",
        meetingsTitle = "Réunions et Visioconférences",
        meetingsSubtitle = "Synchro Google Meet, Zoom, MS Teams",
        meetingMinutesTitle = "Comptes-Rendus et Actions",
        meetingMinutesSubtitle = "Convertissez les points clés en tâches",
        pomodoroSanctuaryTitle = "Sanctuaire de Concentration Pomodoro",
        pomodoroSanctuarySubtitle = "Mode Ne pas déranger et ambiance sonore",
        notesTitle = "Notes, Documents et Savoirs",
        notesSubtitle = "Prise rapide, notes vocales et tags",

        habitsGoalsWellnessHeader = "HABITUDES, OBJECTIFS ET BIEN-ÊTRE",
        habitsTitle = "Habitudes et Séries",
        habitsSubtitle = "Suivi des routines matinales et quotidiennes",
        goalsTitle = "Objectifs et Jalons",
        goalsSubtitle = "Suivi financier, physique et professionnel",
        remindersTitle = "Rappels Intelligents",
        remindersSubtitle = "Déclencheurs par lieu, heure et modules",

        financeBillsCommerceHeader = "FINANCES, FACTURES ET COMMERCE",
        financeDashboardTitle = "Tableau de Bord Financier",
        financeDashboardSubtitle = "Dépenses quotidiennes et budget mensuel",
        subscriptionsTitle = "Abonnements et Dépenses Récurrentes",
        subscriptionsSubtitle = "Factures fibre, énergie, streaming et outils",
        shoppingListsTitle = "Listes de Courses",
        shoppingListsSubtitle = "Budget estimé et organisation par rayons",

        travelSecurityHeader = "VOYAGES, SÉCURITÉ ET CONTACTS",
        travelItineraryTitle = "Itinéraire de Voyage",
        travelItinerarySubtitle = "Vols, réservations et affaires à emporter",
        secureVaultTitle = "Coffre Sécurisé de Documents",
        secureVaultSubtitle = "Passeport, assurances et baux chiffrés",
        contactsTitle = "Contacts et Messages Programmés",
        contactsSubtitle = "Répertoire CRM et rappels d'anniversaires",

        financialHealthTitle = "Santé Financière",
        spendingVelocitySubtitle = "Vélocité des Dépenses",
        budgetTargetLimitButton = "Limite",
        velocityDialTab = "Cadran Vélocité",
        runwayLimitTab = "Marge et Limite",
        statusSafe = "Sûr",
        statusSustainable = "Durable",
        statusCaution = "Prudence",
        statusDanger = "Danger",
        currentSpendOfLimit = "du plafond",

        priorityHigh = "Haute",
        priorityMedium = "Moyenne",
        priorityLow = "Basse",
        autoSortByPriority = "Trier par Priorité",
        actionSave = "Enregistrer",
        actionCancel = "Annuler",
        actionClose = "Fermer",
        actionDone = "Terminé",
        actionEdit = "Modifier",
        actionDelete = "Supprimer",
        today = "Aujourd'hui",
        upcoming = "À venir"
    )

    val german = AppStrings(
        navHome = "Start",
        navCalendar = "Kalender",
        navTasks = "Aufgaben",
        navInsights = "Einblicke",
        navMore = "Mehr",
        navCreate = "Erstellen",

        liveBioSync = "LIVE BIO-SYNC",
        syncedJustNow = "Gerade synchronisiert",
        focusPill = "Fokus",
        focusActivePill = "Fokus AN",
        searchPlaceholder = "Aufgaben, Termine, Rechnungen suchen...",
        notificationsTooltip = "Alle Systeme synchron: Kalender, Gesundheit, Aufgaben & Budget",
        notificationsMutedTooltip = "🤫 Benachrichtigungen stumm: 12 Alarme im Fokusmodus pausiert",
        aiCopilotTooltip = "DayMeet KI-Kopilot",

        focusModeHeader = "FOKUSMODUS AKTIV",
        mutedBadge = "STUMM",
        mutedSubtitle = "12 nicht dringende Alarme stummgeschaltet (Slack, E-Mail)",
        exitFocusButton = "Beenden",
        activeFocusTaskQueue = "FOKUS-AUFGABEN-WARTESCHLANGE",
        subtasksChecklist = "UNTERAUFGABEN-CHECKLISTE",
        markTaskComplete = "Aufgabe abschließen",
        pomodoroFocusTitle = "Tieffokus-Pomodoro",
        timerStart = "Starten",
        timerPause = "Pause",
        focusSanctuaryClearTitle = "Fokusbereich erledigt!",
        focusSanctuaryClearSubtitle = "Alle anstehenden Aufgaben in der Warteschlange abgeschlossen. Gönnen Sie sich eine Pause.",

        commandCenterTitle = "Kommandozentrale",
        commandCenterSubtitle = "Alle Module, Automationen, Finanzen, Gesundheit und Tools",
        languageSectionTitle = "SPRACHE UND LOKALISIERUNG",
        languageCardSubtitle = "Dynamische Mehrsprachigkeit • Sofortiger Sprachwechsel in der App",
        selectLanguageButton = "Sprache ändern",
        searchLanguagePlaceholder = "Sprache oder Land suchen...",
        themeSectionTitle = "SYSTEMDESIGN UND THEME",
        darkModeTitle = "Systemweiter Dunkelmodus",
        darkModeActiveSubtitle = "Tailwind Slate-900 aktiv • Hoher OLED-Kontrast",
        lightModeActiveSubtitle = "Tailwind Hell aktiv • Neutrale Klarheit",
        themeLight = "☀️ Hell",
        themeDark = "🌙 Dunkel (Slate)",
        themeAuto = "⚙️ Automatisch",
        calendarSyncTitle = "Gerätekalender synchronisieren",
        calendarSyncActiveSubtitle = "Aktiv: DayMeet-Alarme werden im lokalen Kalender gespiegelt",
        calendarSyncDisabledSubtitle = "Deaktiviert: Nur interne DayMeet-Meldungen ertönen",

        coreIntelligenceHeader = "KERN-INTELLIGENZ & SYSTEME",
        automationsTitle = "Automationen & Regelwerk",
        automationsSubtitle = "Tägliche Wenn → Falls → Dann Abläufe",
        aiCopilotTitle = "DayMeet KI-Kopilot",
        aiCopilotSubtitle = "Tagesplan-Restrukturierung in natürlicher Sprache",
        dailyBriefingTitle = "Morgen- & Abendbriefing",
        dailyBriefingSubtitle = "Kompakte Übersicht über Termine und Vitalwerte",

        productivityWorkspacesHeader = "PRODUKTIVITÄT & ARBEITSBEREICHE",
        meetingsTitle = "Meetings & Videokonferenzen",
        meetingsSubtitle = "Google Meet, Zoom, MS Teams synchronisieren",
        meetingMinutesTitle = "Protokolle & Maßnahmen",
        meetingMinutesSubtitle = "Kernpunkte in zugewiesene Aufgaben wandeln",
        pomodoroSanctuaryTitle = "Pomodoro-Fokusbereich",
        pomodoroSanctuarySubtitle = "Bitte nicht stören mit Hintergrundklängen",
        notesTitle = "Notizen, Dokumente & Wissen",
        notesSubtitle = "Schnellerfassung, Sprachnotizen & Tags",

        habitsGoalsWellnessHeader = "GEWOHNHEITEN, ZIELE & VITALITÄT",
        habitsTitle = "Gewohnheiten & Serien",
        habitsSubtitle = "Tägliche Routinen und Gewohnheiten verfolgen",
        goalsTitle = "Ziele & Meilensteine",
        goalsSubtitle = "Finanz-, Fitness- und Karriereziele",
        remindersTitle = "Intelligente Erinnerungen",
        remindersSubtitle = "Auslöser nach Ort, Zeit und Modulen",

        financeBillsCommerceHeader = "FINANZEN, RECHNUNGEN & HANDEL",
        financeDashboardTitle = "Finanz-Dashboard & Buch",
        financeDashboardSubtitle = "Tagesausgaben, Monatsbudget & Kategorisierung",
        subscriptionsTitle = "Abos & Wiederkehrende Rechnungen",
        subscriptionsSubtitle = "Strom, Internet, Streaming & Lizenzen",
        shoppingListsTitle = "Einkaufs- & Vorratslisten",
        shoppingListsSubtitle = "Budgetprognose und Artikel-Checklisten",

        travelSecurityHeader = "REISEN, SICHERHEIT & KONTAKTE",
        travelItineraryTitle = "Reiseroute & Trips",
        travelItinerarySubtitle = "Flüge, Hotels & Packliste",
        secureVaultTitle = "Sicherer Dokumentensafe",
        secureVaultSubtitle = "Reisepass, Verträge und Policen lokal verschlüsselt",
        contactsTitle = "Kontakte & Geplante Nachrichten",
        contactsSubtitle = "CRM-Verzeichnis und automatisierte Benachrichtigungen",

        financialHealthTitle = "Finanzielle Gesundheit",
        spendingVelocitySubtitle = "Ausgabengeschwindigkeit",
        budgetTargetLimitButton = "Limit",
        velocityDialTab = "Geschwindigkeits-Tacho",
        runwayLimitTab = "Reichweite & Limit",
        statusSafe = "Sicher",
        statusSustainable = "Nachhaltig",
        statusCaution = "Vorsicht",
        statusDanger = "Gefahr",
        currentSpendOfLimit = "vom Limit",

        priorityHigh = "Hoch",
        priorityMedium = "Mittel",
        priorityLow = "Niedrig",
        autoSortByPriority = "Nach Priorität sortieren",
        actionSave = "Speichern",
        actionCancel = "Abbrechen",
        actionClose = "Schließen",
        actionDone = "Fertig",
        actionEdit = "Bearbeiten",
        actionDelete = "Löschen",
        today = "Heute",
        upcoming = "Demnächst"
    )

    val hindi = AppStrings(
        navHome = "होम",
        navCalendar = "कैलेंडर",
        navTasks = "कार्य",
        navInsights = "विश्लेषण",
        navMore = "अधिक",
        navCreate = "बनाएं",

        liveBioSync = "लाइव बायो-सिंक",
        syncedJustNow = "अभी सिंक हुआ",
        focusPill = "फोकस",
        focusActivePill = "फोकस चालू",
        searchPlaceholder = "कार्य, ईवेंट, बिल खोजें...",
        notificationsTooltip = "सभी सिस्टम सिंक हैं: कैलेंडर, स्वास्थ्य, कार्य और बजट",
        notificationsMutedTooltip = "🤫 सूचनाएं म्यूट हैं: फोकस मोड में 12 गैर-जरूरी अलर्ट शांत किए गए",
        aiCopilotTooltip = "डेमीट एआई कोपायलट",

        focusModeHeader = "फोकस मोड सक्रिय",
        mutedBadge = "म्यूटेड",
        mutedSubtitle = "12 गैर-आवश्यक सूचनाएं शांत हैं (स्लैक, ईमेल व रिमाइंडर)",
        exitFocusButton = "बाहर निकलें",
        activeFocusTaskQueue = "सक्रिय फोकस कार्य कतार",
        subtasksChecklist = "उप-कार्य चेकलिस्ट",
        markTaskComplete = "कार्य पूर्ण चिह्नित करें",
        pomodoroFocusTitle = "डीप फोकस पोमोडोरो",
        timerStart = "शुरू करें",
        timerPause = "रोकें",
        focusSanctuaryClearTitle = "फोकस कतार पूर्ण!",
        focusSanctuaryClearSubtitle = "आपने अपनी कतार के सभी लंबित कार्य पूरे कर लिए हैं। विश्राम करें या डैशबोर्ड पर लौटें।",

        commandCenterTitle = "कमांड सेंटर",
        commandCenterSubtitle = "सभी मॉड्यूल, ऑटोमेशन, वित्त, स्वास्थ्य और उपकरण",
        languageSectionTitle = "भाषा और स्थानीयकरण",
        languageCardSubtitle = "गतिशील बहुभाषी इंजन • तुरंत ऐप-व्यापी भाषा परिवर्तन",
        selectLanguageButton = "भाषा बदलें",
        searchLanguagePlaceholder = "भाषा या देश खोजें...",
        themeSectionTitle = "सिस्टम उपस्थिति और थीम",
        darkModeTitle = "सिस्टम-व्यापी डार्क मोड",
        darkModeActiveSubtitle = "टेलविंड स्लेट-900 सक्रिय • उच्च कंट्रास्ट ओएलईडी",
        lightModeActiveSubtitle = "टेलविंड लाइट सक्रिय • स्वच्छ स्पष्ट थीम",
        themeLight = "☀️ लाइट",
        themeDark = "🌙 डार्क (स्लेट)",
        themeAuto = "⚙️ स्वचालित",
        calendarSyncTitle = "डिवाइस कैलेंडर सूचनाएं सिंक करें",
        calendarSyncActiveSubtitle = "सक्रिय: डेमीट अलर्ट स्थानीय कैलेंडर में दिखाई देंगे",
        calendarSyncDisabledSubtitle = "अक्षम: केवल आंतरिक अलर्ट सूचित करेंगे",

        coreIntelligenceHeader = "मुख्य बुद्धिमत्ता और इंजन",
        automationsTitle = "ऑटोमेशन और नियम इंजन",
        automationsSubtitle = "जब → यदि → तब स्वचालित दैनिक कार्यप्रवाह",
        aiCopilotTitle = "डेमीट एआई कोपायलट",
        aiCopilotSubtitle = "प्राकृतिक भाषा में समय-सारणी का पुनर्गठन",
        dailyBriefingTitle = "सुबह और शाम की ब्रीफिंग",
        dailyBriefingSubtitle = "दिन की प्रतिबद्धताओं और स्वास्थ्य का सारांश",

        productivityWorkspacesHeader = "उत्पादकता और कार्यक्षेत्र",
        meetingsTitle = "बैठकें और वीडियो कॉन्फ्रेंस",
        meetingsSubtitle = "गूगल मीट, जूम, टीम्स सिंक करें",
        meetingMinutesTitle = "बैठक के मिनट्स और एक्शन आइटम",
        meetingMinutesSubtitle = "प्रमुख बिंदुओं को सौंपे गए कार्यों में बदलें",
        pomodoroSanctuaryTitle = "डीप फोकस और पोमोडोरो",
        pomodoroSanctuarySubtitle = "परिवेशी ध्वनियों के साथ डीएनडी मोड",
        notesTitle = "नोट्स, दस्तावेज़ और ज्ञानकोष",
        notesSubtitle = "त्वरित नोट्स, वॉयस रिकॉर्डिंग और टैग",

        habitsGoalsWellnessHeader = "आदतें, लक्ष्य और कल्याण",
        habitsTitle = "आदतें और नियमित सिलसिले",
        habitsSubtitle = "दैनिक आदतों और दिनचर्या पर नज़र रखें",
        goalsTitle = "लक्ष्य और मील के पत्थर",
        goalsSubtitle = "वित्तीय, फिटनेस और करियर लक्ष्यों की ट्रैकिंग",
        remindersTitle = "स्मार्ट रिमाइंडर और स्थान अलर्ट",
        remindersSubtitle = "स्थान, समय और मॉड्यूल आधारित अलर्ट",

        financeBillsCommerceHeader = "वित्त, बिल और वाणिज्य",
        financeDashboardTitle = "वित्त डैशबोर्ड और बहीखाता",
        financeDashboardSubtitle = "दैनिक खर्च, मासिक बजट और वर्गीकरण",
        subscriptionsTitle = "सदस्यता और आवर्ती बिल",
        subscriptionsSubtitle = "बिजली, फाइबर, नेटफ्लिक्स और अन्य खर्चे",
        shoppingListsTitle = "खरीदारी और किराने की सूची",
        shoppingListsSubtitle = "स्वचालित बजट अनुमान और चेकलिस्ट",

        travelSecurityHeader = "यात्रा, सुरक्षा और संचार",
        travelItineraryTitle = "यात्रा कार्यक्रम और यात्राएं",
        travelItinerarySubtitle = "उड़ानें, होटल और पैकिंग सूची",
        secureVaultTitle = "सुरक्षित दस्तावेज़ वॉल्ट",
        secureVaultSubtitle = "पासपोर्ट, बीमा और अनुबंध स्थानीय एन्क्रिप्शन के साथ",
        contactsTitle = "संपर्क और निर्धारित संदेश",
        contactsSubtitle = "सीआरएम निर्देशिका और स्वचालित संदेश",

        financialHealthTitle = "वित्तीय स्वास्थ्य",
        spendingVelocitySubtitle = "खर्च करने की गति",
        budgetTargetLimitButton = "सीमा",
        velocityDialTab = "वेलोसिटी डायल",
        runwayLimitTab = "रनवे और सीमा",
        statusSafe = "सुरक्षित",
        statusSustainable = "स्थायी",
        statusCaution = "सावधानी",
        statusDanger = "खतरा",
        currentSpendOfLimit = "सीमा का",

        priorityHigh = "उच्च",
        priorityMedium = "मध्यम",
        priorityLow = "कम",
        autoSortByPriority = "प्राथमिकता अनुसार क्रमबद्ध करें",
        actionSave = "सहेजें",
        actionCancel = "रद्द करें",
        actionClose = "बंद करें",
        actionDone = "हो गया",
        actionEdit = "संपादित करें",
        actionDelete = "हटाएं",
        today = "आज",
        upcoming = "आगामी"
    )

    val japanese = AppStrings(
        navHome = "ホーム",
        navCalendar = "カレンダー",
        navTasks = "タスク",
        navInsights = "インサイト",
        navMore = "その他",
        navCreate = "作成",

        liveBioSync = "リアルタイム同期",
        syncedJustNow = "たった今同期完了",
        focusPill = "フォーカス",
        focusActivePill = "集中中",
        searchPlaceholder = "タスク、イベント、支出を検索...",
        notificationsTooltip = "全システム同期済み: カレンダー、健康、タスク、予算",
        notificationsMutedTooltip = "🤫 通知ミュート中: フォーカスモードで12件のアラートを停止",
        aiCopilotTooltip = "DayMeet AI コパイロット",

        focusModeHeader = "フォーカスモード稼働中",
        mutedBadge = "ミュート中",
        mutedSubtitle = "12件の非緊急通知をサイレント化 (Slack、メール等)",
        exitFocusButton = "終了",
        activeFocusTaskQueue = "フォーカスタスクキュー",
        subtasksChecklist = "サブタスクチェックリスト",
        markTaskComplete = "タスクを完了にする",
        pomodoroFocusTitle = "ディープフォーカスポモドーロ",
        timerStart = "開始",
        timerPause = "一時停止",
        focusSanctuaryClearTitle = "タスク完了!",
        focusSanctuaryClearSubtitle = "キュー内の保留中タスクがすべて完了しました。休憩を取るかダッシュボードに戻りましょう。",

        commandCenterTitle = "コマンドセンター",
        commandCenterSubtitle = "全モジュール、自動化、財務、健康、個人ツール",
        languageSectionTitle = "言語と地域設定",
        languageCardSubtitle = "動的多言語エンジン • アプリ全体で即時言語切り替え",
        selectLanguageButton = "言語を変更",
        searchLanguagePlaceholder = "言語や国名を検索...",
        themeSectionTitle = "外観とテーマ設定",
        darkModeTitle = "システム全体ダークモード",
        darkModeActiveSubtitle = "Tailwind Slate-900 アクティブ • OLED高コントラスト",
        lightModeActiveSubtitle = "Tailwind ライト アクティブ • ニュートラルテーマ",
        themeLight = "☀️ ライト",
        themeDark = "🌙 ダーク (Slate)",
        themeAuto = "⚙️ 自動",
        calendarSyncTitle = "端末カレンダー通知同期",
        calendarSyncActiveSubtitle = "有効: DayMeetのアラートを端末カレンダーと連携",
        calendarSyncDisabledSubtitle = "無効: DayMeet内蔵アラートのみで通知",

        coreIntelligenceHeader = "コアインテリジェンス機能",
        automationsTitle = "自動化ルールエンジン",
        automationsSubtitle = "いつ → もし → その時 自動ワークフロー",
        aiCopilotTitle = "DayMeet AI コパイロット",
        aiCopilotSubtitle = "自然言語によるスケジュールの最適化・提案",
        dailyBriefingTitle = "朝と夜のブリーフィング",
        dailyBriefingSubtitle = "本日の予定とバイタルのハイレベル要約",

        productivityWorkspacesHeader = "生産性とワークスペース",
        meetingsTitle = "ミーティングとビデオ通話",
        meetingsSubtitle = "Google Meet、Zoom、MS Teamsと参加者同期",
        meetingMinutesTitle = "議事録とアクション項目",
        meetingMinutesSubtitle = "要点を担当タスクへ即時変換",
        pomodoroSanctuaryTitle = "ポモドーロ集中スペース",
        pomodoroSanctuarySubtitle = "環境音と応答不可モード",
        notesTitle = "ノート・文書・ナレッジ",
        notesSubtitle = "クイックメモ、音声入力、タグ管理",

        habitsGoalsWellnessHeader = "習慣・目標・ウェルネス",
        habitsTitle = "習慣と連続記録",
        habitsSubtitle = "毎日の習慣と朝のルーティンを記録",
        goalsTitle = "目標とマイルストーン",
        goalsSubtitle = "財務、フィットネス、キャリア目標の追跡",
        remindersTitle = "スマートリマインダー",
        remindersSubtitle = "位置・時間・モジュール連動アラート",

        financeBillsCommerceHeader = "財務・請求・支出",
        financeDashboardTitle = "財務ダッシュボードと帳簿",
        financeDashboardSubtitle = "日々の支出、月間予算、自動カテゴリ分類",
        subscriptionsTitle = "サブスクと定期支払い",
        subscriptionsSubtitle = "光熱費、回線、動画配信、ツールの支払い管理",
        shoppingListsTitle = "買い物リスト",
        shoppingListsSubtitle = "予算見積もりと売り場チェックリスト",

        travelSecurityHeader = "旅行・セキュリティ・連絡先",
        travelItineraryTitle = "旅行日程と旅程",
        travelItinerarySubtitle = "フライト、ホテル予約、持ち物リスト",
        secureVaultTitle = "安全なドキュメント保管庫",
        secureVaultSubtitle = "パスポートや契約書をローカル暗号化",
        contactsTitle = "連絡先と予約メッセージ",
        contactsSubtitle = "CRMディレクトリと自動誕生日メッセージ",

        financialHealthTitle = "財務健全性",
        spendingVelocitySubtitle = "支出速度",
        budgetTargetLimitButton = "上限設定",
        velocityDialTab = "速度メーター",
        runwayLimitTab = "残日数と上限",
        statusSafe = "安全",
        statusSustainable = "適正",
        statusCaution = "注意",
        statusDanger = "危険",
        currentSpendOfLimit = "上限比",

        priorityHigh = "高",
        priorityMedium = "中",
        priorityLow = "低",
        autoSortByPriority = "優先度順で自動並べ替え",
        actionSave = "保存",
        actionCancel = "キャンセル",
        actionClose = "閉じる",
        actionDone = "完了",
        actionEdit = "編集",
        actionDelete = "削除",
        today = "今日",
        upcoming = "今後"
    )

    val chinese = AppStrings(
        navHome = "首页",
        navCalendar = "日历",
        navTasks = "任务",
        navInsights = "洞察",
        navMore = "更多",
        navCreate = "创建",

        liveBioSync = "实时健康同步",
        syncedJustNow = "刚刚已同步",
        focusPill = "专注",
        focusActivePill = "专注中",
        searchPlaceholder = "搜索任务、日程、账单...",
        notificationsTooltip = "所有系统已同步：日历、健康、任务与预算",
        notificationsMutedTooltip = "🤫 通知已静音：专注模式下已静音12项非紧急提醒",
        aiCopilotTooltip = "DayMeet AI 助手",

        focusModeHeader = "专注模式已开启",
        mutedBadge = "静音中",
        mutedSubtitle = "已静音12项非紧急通知 (Slack、邮件与提醒)",
        exitFocusButton = "退出",
        activeFocusTaskQueue = "专注任务队列",
        subtasksChecklist = "子任务清单",
        markTaskComplete = "标记任务为已完成",
        pomodoroFocusTitle = "深度专注番茄钟",
        timerStart = "开始",
        timerPause = "暂停",
        focusSanctuaryClearTitle = "专注任务已全部完成！",
        focusSanctuaryClearSubtitle = "您已完成队列中的所有待办事项。稍作休息或返回主页控制面板。",

        commandCenterTitle = "控制中心",
        commandCenterSubtitle = "全部模块、自动化规则、财务、健康与个人工具",
        languageSectionTitle = "语言与本地化",
        languageCardSubtitle = "动态多语言引擎 • 全应用即时无缝切换",
        selectLanguageButton = "切换语言",
        searchLanguagePlaceholder = "搜索语言或国家...",
        themeSectionTitle = "系统外观与主题",
        darkModeTitle = "系统级深色模式",
        darkModeActiveSubtitle = "Tailwind Slate-900 启用 • 高对比度 OLED",
        lightModeActiveSubtitle = "Tailwind 浅色启用 • 清晰自然主题",
        themeLight = "☀️ 浅色",
        themeDark = "🌙 深色 (Slate)",
        themeAuto = "⚙️ 自动",
        calendarSyncTitle = "同步设备日历提醒",
        calendarSyncActiveSubtitle = "已启用：DayMeet 提醒同步至本地系统日历",
        calendarSyncDisabledSubtitle = "已禁用：仅应用内提醒有效",

        coreIntelligenceHeader = "核心智能引擎",
        automationsTitle = "自动化规则引擎",
        automationsSubtitle = "何时 → 如果 → 那么 自动化每日工作流",
        aiCopilotTitle = "DayMeet AI 助手",
        aiCopilotSubtitle = "自然语言行程重组与智能洞察",
        dailyBriefingTitle = "早晚日程简报",
        dailyBriefingSubtitle = "今日核心事务与身体指标概览",

        productivityWorkspacesHeader = "效率工作区",
        meetingsTitle = "会议与视频日程",
        meetingsSubtitle = "同步 Google Meet、Zoom、MS Teams 与参会人员",
        meetingMinutesTitle = "会议纪要与行动项",
        meetingMinutesSubtitle = "快速将发言要点转化为分配任务",
        pomodoroSanctuaryTitle = "深度专注番茄钟庇护所",
        pomodoroSanctuarySubtitle = "免打扰白噪音与自动回复",
        notesTitle = "随手记、文档与知识库",
        notesSubtitle = "快速记录、语音便签与多标签整理",

        habitsGoalsWellnessHeader = "习惯、目标与健康",
        habitsTitle = "习惯打卡与连击",
        habitsSubtitle = "追踪每日习惯与晨间日程",
        goalsTitle = "目标与里程碑",
        goalsSubtitle = "财务、健身与职业目标阶段追踪",
        remindersTitle = "智能提醒与位置闹钟",
        remindersSubtitle = "基于位置、时间与模块联动的智能触发器",

        financeBillsCommerceHeader = "财务、账单与日常消费",
        financeDashboardTitle = "财务看板与账本",
        financeDashboardSubtitle = "日常支出明细、月度预算与智能分类",
        subscriptionsTitle = "订阅与周期账单",
        subscriptionsSubtitle = "水电宽带、流媒体与软件服务到期管理",
        shoppingListsTitle = "购物与超市清单",
        shoppingListsSubtitle = "自动预算估算与分类货架核对",

        travelSecurityHeader = "行程、隐私与人脉",
        travelItineraryTitle = "差旅行程与游记",
        travelItinerarySubtitle = "航班、酒店预订与行前行李打包清单",
        secureVaultTitle = "安全机密文档库",
        secureVaultSubtitle = "护照、保险与合同本地端到端加密存储",
        contactsTitle = "人脉与定时消息",
        contactsSubtitle = "客户关系目录与自动化生日祝福",

        financialHealthTitle = "财务健康",
        spendingVelocitySubtitle = "消费支出流速",
        budgetTargetLimitButton = "限额",
        velocityDialTab = "流速仪表盘",
        runwayLimitTab = "可用天数与限额",
        statusSafe = "安全",
        statusSustainable = "稳健",
        statusCaution = "警惕",
        statusDanger = "超支",
        currentSpendOfLimit = "占预算限额",

        priorityHigh = "高",
        priorityMedium = "中",
        priorityLow = "低",
        autoSortByPriority = "按优先级自动排序",
        actionSave = "保存",
        actionCancel = "取消",
        actionClose = "关闭",
        actionDone = "完成",
        actionEdit = "编辑",
        actionDelete = "删除",
        today = "今天",
        upcoming = "即将到来"
    )

    val arabic = AppStrings(
        navHome = "الرئيسية",
        navCalendar = "التقويم",
        navTasks = "المهام",
        navInsights = "التحليلات",
        navMore = "المزيد",
        navCreate = "إنشاء",

        liveBioSync = "المزامنة الحيوية المباشرة",
        syncedJustNow = "تمت المزامنة للتو",
        focusPill = "التركيز",
        focusActivePill = "التركيز نشط",
        searchPlaceholder = "البحث عن المهام، الأحداث، الفواتير...",
        notificationsTooltip = "جميع الأنظمة متزامنة: التقويم والصحة والمهام والميزانية",
        notificationsMutedTooltip = "🤫 كتم الإشعارات: تم إسكات 12 تنبيهاً غير عاجل في وضع التركيز",
        aiCopilotTooltip = "مساعد DayMeet الذكي",

        focusModeHeader = "وضع التركيز نشط",
        mutedBadge = "مكتوم",
        mutedSubtitle = "تم كتم 12 تنبيهاً غير عاجل (Slack، البريد، والتذكيرات)",
        exitFocusButton = "خروج",
        activeFocusTaskQueue = "قائمة مهام التركيز النشطة",
        subtasksChecklist = "قائمة المهام الفرعية",
        markTaskComplete = "تحديد المهمة كمكتملة",
        pomodoroFocusTitle = "بومودورو التركيز العميق",
        timerStart = "بدء",
        timerPause = "إيقاف مؤقت",
        focusSanctuaryClearTitle = "تم إنجاز مهام التركيز!",
        focusSanctuaryClearSubtitle = "لقد أكملت جميع المهام في قائمة الانتظار. خذ استراحة أو ارجع إلى لوحة التحكم.",

        commandCenterTitle = "مركز القيادة",
        commandCenterSubtitle = "جميع الوحدات، الأتمتة، المالية، الصحة، والأدوات الشخصية",
        languageSectionTitle = "اللغة والترجمة",
        languageCardSubtitle = "محرك متعدد اللغات ديناميكي • تبديل فوري عبر التطبيق بأكمله",
        selectLanguageButton = "تغيير اللغة",
        searchLanguagePlaceholder = "ابحث عن لغة أو دولة...",
        themeSectionTitle = "مظهر النظام والسمة",
        darkModeTitle = "الوضع الداكن للنظام",
        darkModeActiveSubtitle = "لوحة Tailwind Slate-900 نشطة • تباين OLED عالي",
        lightModeActiveSubtitle = "لوحة Tailwind الفاتحة نشطة • سمة محايدة واضحة",
        themeLight = "☀️ فاتح",
        themeDark = "🌙 داكن",
        themeAuto = "⚙️ تلقائي",
        calendarSyncTitle = "مزامنة تنبيهات تقويم الجهاز",
        calendarSyncActiveSubtitle = "نشط: يتم عرض تنبيهات DayMeet في تقويم الجهاز المحلي",
        calendarSyncDisabledSubtitle = "معطل: ستصدر التنبيهات من داخل التطبيق فقط",

        coreIntelligenceHeader = "محركات الذكاء الأساسية",
        automationsTitle = "محرك القواعد والأتمتة",
        automationsSubtitle = "سير العمل اليومي التلقائي عند → إذا → إذن",
        aiCopilotTitle = "مساعد DayMeet الذكي",
        aiCopilotSubtitle = "إعادة هيكلة الجداول باللغة الطبيعية والتحليلات",
        dailyBriefingTitle = "الموجز الصباحي والمسائي",
        dailyBriefingSubtitle = "ملخص رفيع المستوى للالتزامات اليومية والمؤشرات",

        productivityWorkspacesHeader = "الإنتاجية ومساحات العمل",
        meetingsTitle = "الاجتماعات ومؤتمرات الفيديو",
        meetingsSubtitle = "مزامنة Google Meet وZoom وTeams والحضور",
        meetingMinutesTitle = "محاضر الاجتماعات وبنود العمل",
        meetingMinutesSubtitle = "تحويل الملاحظات إلى مهام مخصصة",
        pomodoroSanctuaryTitle = "ملاذ التركيز وبومودورو",
        pomodoroSanctuarySubtitle = "وضع عدم الإزعاج مع أصوات هادئة ورد تلقائي",
        notesTitle = "الملاحظات والمستندات وقاعدة المعرفة",
        notesSubtitle = "تدوين سريع وملاحظات صوتية وتصنيفات",

        habitsGoalsWellnessHeader = "العادات والأهداف والصحة",
        habitsTitle = "العادات والسلاسل اليومية",
        habitsSubtitle = "تتبع العادات اليومية والروتين الصباحي",
        goalsTitle = "الأهداف والمراحل",
        goalsSubtitle = "تتبع الأهداف المالية والبدنية والمهنية",
        remindersTitle = "التذكيرات الذكية وتنبيهات الموقع",
        remindersSubtitle = "تنبيهات مرتبطة بالموقع والوقت والوحدات",

        financeBillsCommerceHeader = "المالية والفواتير والتسوق",
        financeDashboardTitle = "لوحة المالية وسجل الحسابات",
        financeDashboardSubtitle = "الإنفاق اليومي والميزانية الشهرية والتصنيف التلقائي",
        subscriptionsTitle = "الاشتراكات والفواتير الدورية",
        subscriptionsSubtitle = "الكهرباء والإنترنت والاشتراكات الشهرية",
        shoppingListsTitle = "قوائم التسوق والبقالة",
        shoppingListsSubtitle = "تقدير تلقائي للميزانية وتصنيف الأصناف",

        travelSecurityHeader = "السفر والأمان وجهات الاتصال",
        travelItineraryTitle = "خطة السفر والرحلات",
        travelItinerarySubtitle = "الرحلات الجوية والفنادق وقائمة الحقائب",
        secureVaultTitle = "خزينة المستندات الآمنة",
        secureVaultSubtitle = "جوازات السفر والعقود بتشفير محلي",
        contactsTitle = "جهات الاتصال والرسائل المجدولة",
        contactsSubtitle = "دليل العلاقات والتنبيهات المجدولة",

        financialHealthTitle = "الصحة المالية",
        spendingVelocitySubtitle = "سرعة الإنفاق",
        budgetTargetLimitButton = "الحد الأقصى",
        velocityDialTab = "مؤشر السرعة",
        runwayLimitTab = "المهلة والحد",
        statusSafe = "آمن",
        statusSustainable = "مستدام",
        statusCaution = "حذر",
        statusDanger = "خطر",
        currentSpendOfLimit = "من الحد",

        priorityHigh = "عالية",
        priorityMedium = "متوسطة",
        priorityLow = "منخفضة",
        autoSortByPriority = "ترتيب تلقائي حسب الأولوية",
        actionSave = "حفظ",
        actionCancel = "إلغاء",
        actionClose = "إغلاق",
        actionDone = "تم",
        actionEdit = "تعديل",
        actionDelete = "حذف",
        today = "اليوم",
        upcoming = "القادم"
    )

    val portuguese = AppStrings(
        navHome = "Início",
        navCalendar = "Calendário",
        navTasks = "Tarefas",
        navInsights = "Estatísticas",
        navMore = "Mais",
        navCreate = "Criar",

        liveBioSync = "BIO-SINCRONIZAÇÃO",
        syncedJustNow = "Sincronizado agora",
        focusPill = "Foco",
        focusActivePill = "Foco ATIVO",
        searchPlaceholder = "Buscar tarefas, eventos, contas...",
        notificationsTooltip = "Sistemas sincronizados: Calendário, Saúde, Tarefas e Orçamento",
        notificationsMutedTooltip = "🤫 Notificações silenciadas: 12 alertas pausados no Modo Foco",
        aiCopilotTooltip = "Copiloto IA DayMeet",

        focusModeHeader = "MODO FOCO ATIVO",
        mutedBadge = "SILENCIADO",
        mutedSubtitle = "12 alertas não urgentes silenciados (Slack, e-mail)",
        exitFocusButton = "Sair",
        activeFocusTaskQueue = "FILA DE TAREFAS EM FOCO",
        subtasksChecklist = "LISTA DE SUBTAREFAS",
        markTaskComplete = "Marcar Tarefa como Concluída",
        pomodoroFocusTitle = "Pomodoro de Foco Profundo",
        timerStart = "Iniciar",
        timerPause = "Pausar",
        focusSanctuaryClearTitle = "Foco Concluído!",
        focusSanctuaryClearSubtitle = "Você concluiu todas as tarefas pendentes na fila. Descanse ou volte ao painel.",

        commandCenterTitle = "Central de Comando",
        commandCenterSubtitle = "Módulos, automações, finanças, saúde e ferramentas pessoais",
        languageSectionTitle = "IDIOMA E LOCALIZAÇÃO",
        languageCardSubtitle = "Motor dinâmico multilíngue • Troca instantânea em todo o app",
        selectLanguageButton = "Alterar Idioma",
        searchLanguagePlaceholder = "Buscar idioma ou país...",
        themeSectionTitle = "APARÊNCIA DO SISTEMA E TEMA",
        darkModeTitle = "Modo Escuro Global",
        darkModeActiveSubtitle = "Tela Tailwind Slate-900 ativa • Alto contraste OLED",
        lightModeActiveSubtitle = "Tela Tailwind Clara ativa • Tema neutro de alta clareza",
        themeLight = "☀️ Claro",
        themeDark = "🌙 Escuro (Slate)",
        themeAuto = "⚙️ Automático",
        calendarSyncTitle = "Sincronizar Alertas do Calendário",
        calendarSyncActiveSubtitle = "Ativo: Alertas do DayMeet integrados ao calendário local",
        calendarSyncDisabledSubtitle = "Desativado: Apenas alertas internos avisarão",

        coreIntelligenceHeader = "INTELIGÊNCIA CENTRAL E MOTORES",
        automationsTitle = "Motor de Regras e Automações",
        automationsSubtitle = "Fluxos diários automatizados Quando → Se → Então",
        aiCopilotTitle = "Copiloto IA DayMeet",
        aiCopilotSubtitle = "Reorganização de rotina e horários em linguagem natural",
        dailyBriefingTitle = "Briefing Matinal e Noturno",
        dailyBriefingSubtitle = "Resumo executivo de compromissos e métricas vitais",

        productivityWorkspacesHeader = "PRODUTIVIDADE E ESPAÇOS DE TRABALHO",
        meetingsTitle = "Reuniões e Videoconferências",
        meetingsSubtitle = "Sincronize Google Meet, Zoom, MS Teams e participantes",
        meetingMinutesTitle = "Atas de Reunião e Ações",
        meetingMinutesSubtitle = "Converta anotações em tarefas atribuídas",
        pomodoroSanctuaryTitle = "Santuário de Concentração Pomodoro",
        pomodoroSanctuarySubtitle = "Modo Não Perturbe com sons relaxantes",
        notesTitle = "Notas, Documentos e Conhecimento",
        notesSubtitle = "Captura rápida, notas de voz e etiquetas",

        habitsGoalsWellnessHeader = "HÁBITOS, METAS E BEM-ESTAR",
        habitsTitle = "Hábitos e Sequências",
        habitsSubtitle = "Acompanhamento diário de hábitos e rotinas",
        goalsTitle = "Metas e Marcos",
        goalsSubtitle = "Metas financeiras, físicas e profissionais",
        remindersTitle = "Lembretes Inteligentes",
        remindersSubtitle = "Disparadores por localização e horário",

        financeBillsCommerceHeader = "FINANÇAS, CONTAS E COMPRAS",
        financeDashboardTitle = "Painel Financeiro e Livro-Caixa",
        financeDashboardSubtitle = "Gastos diários, orçamento mensal e categorias automáticas",
        subscriptionsTitle = "Assinaturas e Contas Recorrentes",
        subscriptionsSubtitle = "Luz, Internet, Netflix e despesas periódicas",
        shoppingListsTitle = "Listas de Compras e Mercado",
        shoppingListsSubtitle = "Estimativa automática de orçamento e corredores",

        travelSecurityHeader = "VIAGENS, SEGURANÇA E CONTATOS",
        travelItineraryTitle = "Itinerário de Viagens",
        travelItinerarySubtitle = "Voos, reservas de hotéis e lista de malas",
        secureVaultTitle = "Cofre Seguro de Documentos",
        secureVaultSubtitle = "Passaporte, contratos e certidões criptografadas",
        contactsTitle = "Contatos e Mensagens Agendadas",
        contactsSubtitle = "Diretório CRM e mensagens automáticas",

        financialHealthTitle = "Saúde Financeira",
        spendingVelocitySubtitle = "Velocidade de Gastos",
        budgetTargetLimitButton = "Limite",
        velocityDialTab = "Mostrador de Velocidade",
        runwayLimitTab = "Margem e Limite",
        statusSafe = "Seguro",
        statusSustainable = "Sustentável",
        statusCaution = "Atenção",
        statusDanger = "Perigo",
        currentSpendOfLimit = "do limite",

        priorityHigh = "Alta",
        priorityMedium = "Média",
        priorityLow = "Baixa",
        autoSortByPriority = "Ordenar por Prioridade",
        actionSave = "Salvar",
        actionCancel = "Cancelar",
        actionClose = "Fechar",
        actionDone = "Concluído",
        actionEdit = "Editar",
        actionDelete = "Excluir",
        today = "Hoje",
        upcoming = "Próximos"
    )

    val russian = AppStrings(
        navHome = "Главная",
        navCalendar = "Календарь",
        navTasks = "Задачи",
        navInsights = "Аналитика",
        navMore = "Ещё",
        navCreate = "Создать",

        liveBioSync = "СИНХРОНИЗАЦИЯ",
        syncedJustNow = "Синхронизировано только что",
        focusPill = "Фокус",
        focusActivePill = "Фокус ВКЛ",
        searchPlaceholder = "Поиск задач, событий, счетов...",
        notificationsTooltip = "Все системы синхронизированы: Календарь, Здоровье, Задачи и Бюджет",
        notificationsMutedTooltip = "🤫 Уведомления отключены: 12 несрочных оповещений заглушены",
        aiCopilotTooltip = "DayMeet ИИ-Копилот",

        focusModeHeader = "РЕЖИМ ФОКУСА ВКЛЮЧЕН",
        mutedBadge = "БЕЗ ЗВУКА",
        mutedSubtitle = "12 несрочных оповещений заглушены (Slack, почта и напоминания)",
        exitFocusButton = "Выход",
        activeFocusTaskQueue = "ОЧЕРЕДЬ ЗАДАЧ В ФОКУСЕ",
        subtasksChecklist = "СПИСОК ПОДЗАДАЧ",
        markTaskComplete = "Отметить выполненной",
        pomodoroFocusTitle = "Помодоро глубокого фокуса",
        timerStart = "Старт",
        timerPause = "Пауза",
        focusSanctuaryClearTitle = "Все задачи завершены!",
        focusSanctuaryClearSubtitle = "Вы завершили все текущие задачи в очереди. Отдохните или вернитесь к обзору.",

        commandCenterTitle = "Командный центр",
        commandCenterSubtitle = "Все модули, автоматизации, финансы, здоровье и инструменты",
        languageSectionTitle = "ЯЗЫК И ЛОКАЛИЗАЦИЯ",
        languageCardSubtitle = "Динамический мультиязычный движок • Мгновенное переключение языка",
        selectLanguageButton = "Сменить язык",
        searchLanguagePlaceholder = "Поиск языка или страны...",
        themeSectionTitle = "ВНЕШНИЙ ВИД И ТЕМА",
        darkModeTitle = "Системная темная тема",
        darkModeActiveSubtitle = "Tailwind Slate-900 активна • Высокий контраст OLED",
        lightModeActiveSubtitle = "Tailwind Светлая активна • Чистая нейтральная тема",
        themeLight = "☀️ Светлая",
        themeDark = "🌙 Темная (Slate)",
        themeAuto = "⚙️ Авто",
        calendarSyncTitle = "Синхронизация с системным календарем",
        calendarSyncActiveSubtitle = "Включено: Оповещения DayMeet дублируются в календаре устройства",
        calendarSyncDisabledSubtitle = "Отключено: Уведомления будут только внутри приложения",

        coreIntelligenceHeader = "ОСНОВНЫЕ ИИ-СИСТЕМЫ",
        automationsTitle = "Движок правил и автоматизаций",
        automationsSubtitle = "Автоматические ежедневные цепочки Когда → Если → То",
        aiCopilotTitle = "DayMeet ИИ-Копилот",
        aiCopilotSubtitle = "Оптимизация расписания на естественном языке",
        dailyBriefingTitle = "Утренний и вечерний брифинг",
        dailyBriefingSubtitle = "Краткий обзор встреч, планов и показателей",

        productivityWorkspacesHeader = "ПРОДУКТИВНОСТЬ И РАБОЧИЕ ОБЛАСТИ",
        meetingsTitle = "Встречи и видеоконференции",
        meetingsSubtitle = "Синхронизация Google Meet, Zoom, MS Teams",
        meetingMinutesTitle = "Итоги встреч и действия",
        meetingMinutesSubtitle = "Превращение заметок в назначенные задачи",
        pomodoroSanctuaryTitle = "Пространство фокуса Помодоро",
        pomodoroSanctuarySubtitle = "Режим не беспокоить с фоновыми звуками",
        notesTitle = "Заметки, документы и база знаний",
        notesSubtitle = "Быстрые заметки, аудиозаписи и теги",

        habitsGoalsWellnessHeader = "ПРИВЫЧКИ, ЦЕЛИ И ЗДОРОВЬЕ",
        habitsTitle = "Привычки и серии дней",
        habitsSubtitle = "Отслеживание полезных привычек и ритуалов",
        goalsTitle = "Цели и ориентиры",
        goalsSubtitle = "Финансовые, спортивные и карьерные цели",
        remindersTitle = "Умные напоминания",
        remindersSubtitle = "Срабатывание по месту, времени и событиям",

        financeBillsCommerceHeader = "ФИНАНСЫ, СЧЕТА И ТРАТЫ",
        financeDashboardTitle = "Финансовая панель и баланс",
        financeDashboardSubtitle = "Расходы за день, месячный бюджет и автокатегории",
        subscriptionsTitle = "Подписки и регулярные платежи",
        subscriptionsSubtitle = "ЖКХ, интернет, стриминг и сервисы",
        shoppingListsTitle = "Списки покупок",
        shoppingListsSubtitle = "Оценка расходов и чеклист покупок",

        travelSecurityHeader = "ПУТЕШЕСТВИЯ И БЕЗОПАСНОСТЬ",
        travelItineraryTitle = "Маршруты и поездки",
        travelItinerarySubtitle = "Авиабилеты, отели и чеклист багажа",
        secureVaultTitle = "Защищенное хранилище документов",
        secureVaultSubtitle = "Паспорта и договоры с локальным шифрованием",
        contactsTitle = "Контакты и отложенные сообщения",
        contactsSubtitle = "CRM-каталог и поздравления с праздниками",

        financialHealthTitle = "Финансовое здоровье",
        spendingVelocitySubtitle = "Скорость расходования",
        budgetTargetLimitButton = "Лимит",
        velocityDialTab = "Спидометр трат",
        runwayLimitTab = "Запас и лимит",
        statusSafe = "Безопасно",
        statusSustainable = "В норме",
        statusCaution = "Осторожно",
        statusDanger = "Перерасход",
        currentSpendOfLimit = "от лимита",

        priorityHigh = "Высокий",
        priorityMedium = "Средний",
        priorityLow = "Низкий",
        autoSortByPriority = "Сортировать по приоритету",
        actionSave = "Сохранить",
        actionCancel = "Отмена",
        actionClose = "Закрыть",
        actionDone = "Готово",
        actionEdit = "Изменить",
        actionDelete = "Удалить",
        today = "Сегодня",
        upcoming = "Скоро"
    )

    val italian = AppStrings(
        navHome = "Home",
        navCalendar = "Calendario",
        navTasks = "Attività",
        navInsights = "Analisi",
        navMore = "Altro",
        navCreate = "Crea",

        liveBioSync = "BIO-SYNC ATTIVO",
        syncedJustNow = "Sincronizzato ora",
        focusPill = "Focus",
        focusActivePill = "Focus ATTIVO",
        searchPlaceholder = "Cerca attività, eventi, spese...",
        notificationsTooltip = "Tutti i sistemi sincronizzati: Calendario, Salute, Attività e Budget",
        notificationsMutedTooltip = "🤫 Notifiche silenziate: 12 avvisi non urgenti in modalità Focus",
        aiCopilotTooltip = "DayMeet Copilota IA",

        focusModeHeader = "MODALITÀ FOCUS ATTIVA",
        mutedBadge = "SILENZIOSO",
        mutedSubtitle = "12 avvisi non urgenti silenziati (Slack, email e promemoria)",
        exitFocusButton = "Esci",
        activeFocusTaskQueue = "CODA ATTIVITÀ IN FOCUS",
        subtasksChecklist = "CHECKLIST SOTTO-ATTIVITÀ",
        markTaskComplete = "Segna come completata",
        pomodoroFocusTitle = "Pomodoro Concentrazione Profonda",
        timerStart = "Avvia",
        timerPause = "Pausa",
        focusSanctuaryClearTitle = "Attività completate!",
        focusSanctuaryClearSubtitle = "Hai completato tutte le attività in coda. Fai una pausa o torna al pannello principale.",

        commandCenterTitle = "Centro di Controllo",
        commandCenterSubtitle = "Tutti i moduli, automazioni, finanze, salute e strumenti personali",
        languageSectionTitle = "LINGUA E LOCALIZZAZIONE",
        languageCardSubtitle = "Motore multilingue dinamico • Cambio istantaneo in tutta l'applicazione",
        selectLanguageButton = "Cambia Lingua",
        searchLanguagePlaceholder = "Cerca lingua o paese...",
        themeSectionTitle = "ASPETTO DEL SISTEMA E TEMA",
        darkModeTitle = "Tema Scuro di Sistema",
        darkModeActiveSubtitle = "Sfondo Tailwind Slate-900 attivo • Alto contrasto OLED",
        lightModeActiveSubtitle = "Sfondo Tailwind Chiaro attivo • Chiarezza neutra",
        themeLight = "☀️ Chiaro",
        themeDark = "🌙 Scuro (Slate)",
        themeAuto = "⚙️ Automatico",
        calendarSyncTitle = "Sincronizza Notifiche Calendario",
        calendarSyncActiveSubtitle = "Attivo: Gli avvisi DayMeet sono replicati nel calendario locale",
        calendarSyncDisabledSubtitle = "Disattivato: Suoneranno solo le notifiche interne",

        coreIntelligenceHeader = "INTELLIGENZA E MOTORI PRINCIPALI",
        automationsTitle = "Motore di Regole e Automazioni",
        automationsSubtitle = "Flussi quotidiani Quando → Se → Allora",
        aiCopilotTitle = "DayMeet Copilota IA",
        aiCopilotSubtitle = "Riorganizzazione del programma in linguaggio naturale",
        dailyBriefingTitle = "Briefing Mattutino e Serale",
        dailyBriefingSubtitle = "Sintesi degli impegni e parametri vitali della giornata",

        productivityWorkspacesHeader = "PRODUTTIVITÀ E SPAZI DI LAVORO",
        meetingsTitle = "Riunioni e Videoconferenze",
        meetingsSubtitle = "Sincronizza Google Meet, Zoom, MS Teams e partecipanti",
        meetingMinutesTitle = "Verbali e Azioni",
        meetingMinutesSubtitle = "Converti i punti chiave in attività assegnate",
        pomodoroSanctuaryTitle = "Spazio Pomodoro per la Concentrazione",
        pomodoroSanctuarySubtitle = "Modalità Non Disturbare con suoni rilassanti",
        notesTitle = "Note, Documenti e Conoscenza",
        notesSubtitle = "Note rapide, promemoria vocali e tag",

        habitsGoalsWellnessHeader = "ABITUDINI, OBIETTIVI E BENESSERE",
        habitsTitle = "Abitudini e Routine",
        habitsSubtitle = "Monitora abitudini quotidiane e routine mattutine",
        goalsTitle = "Obiettivi e Traguardi",
        goalsSubtitle = "Monitoraggio finanziario, fitness e carriera",
        remindersTitle = "Promemoria Intelligenti",
        remindersSubtitle = "Attivazione per posizione, orario e moduli",

        financeBillsCommerceHeader = "FINANZE, SPESE E COMMERCIO",
        financeDashboardTitle = "Pannello Finanziario e Registro",
        financeDashboardSubtitle = "Spese giornaliere, budget mensile e categorie automatiche",
        subscriptionsTitle = "Abbonamenti e Spese Ricorrenti",
        subscriptionsSubtitle = "Luce, Internet, streaming e utenze",
        shoppingListsTitle = "Liste della Spesa",
        shoppingListsSubtitle = "Stima automatica del budget e suddivisione corsie",

        travelSecurityHeader = "VIAGGI, SICUREZZA E CONTATTI",
        travelItineraryTitle = "Itinerario e Viaggi",
        travelItinerarySubtitle = "Voli, hotel e lista bagagli",
        secureVaultTitle = "Cassaforte Sicura dei Documenti",
        secureVaultSubtitle = "Passaporto, assicurazione e contratti crittografati",
        contactsTitle = "Contatti e Messaggi Programmati",
        contactsSubtitle = "Rubrica CRM e auguri automatici",

        financialHealthTitle = "Salute Finanziaria",
        spendingVelocitySubtitle = "Velocità di Spesa",
        budgetTargetLimitButton = "Limite",
        velocityDialTab = "Quadrante Velocità",
        runwayLimitTab = "Margine e Limite",
        statusSafe = "Sicuro",
        statusSustainable = "Sostenibile",
        statusCaution = "Attenzione",
        statusDanger = "Pericolo",
        currentSpendOfLimit = "del limite",

        priorityHigh = "Alta",
        priorityMedium = "Media",
        priorityLow = "Bassa",
        autoSortByPriority = "Ordina per Priorità",
        actionSave = "Salva",
        actionCancel = "Annulla",
        actionClose = "Chiudi",
        actionDone = "Fatto",
        actionEdit = "Modifica",
        actionDelete = "Elimina",
        today = "Oggi",
        upcoming = "In arrivo"
    )

    val korean = AppStrings(
        navHome = "홈",
        navCalendar = "캘린더",
        navTasks = "할 일",
        navInsights = "인사이트",
        navMore = "더보기",
        navCreate = "생성",

        liveBioSync = "실시간 바이오 동기화",
        syncedJustNow = "방금 동기화됨",
        focusPill = "몰입",
        focusActivePill = "몰입 모드",
        searchPlaceholder = "할 일, 일정, 지출 검색...",
        notificationsTooltip = "모든 시스템 동기화됨: 캘린더, 건강, 할 일, 예산",
        notificationsMutedTooltip = "🤫 알림 음소거됨: 몰입 모드에서 12개의 비긴급 알림 차단",
        aiCopilotTooltip = "DayMeet AI 코파일럿",

        focusModeHeader = "몰입 모드 활성화",
        mutedBadge = "음소거",
        mutedSubtitle = "12개의 비긴급 알림이 음소거되었습니다 (Slack, 이메일 등)",
        exitFocusButton = "종료",
        activeFocusTaskQueue = "활성 몰입 할 일 대기열",
        subtasksChecklist = "세부 작업 체크리스트",
        markTaskComplete = "작업 완료 표시",
        pomodoroFocusTitle = "딥 포커스 뽀모도로",
        timerStart = "시작",
        timerPause = "일시정지",
        focusSanctuaryClearTitle = "몰입 작업 완료!",
        focusSanctuaryClearSubtitle = "대기열의 모든 할 일을 완료했습니다. 잠시 휴식을 취하거나 대시보드로 돌아가세요.",

        commandCenterTitle = "컨트롤 센터",
        commandCenterSubtitle = "모든 모듈, 자동화, 재정, 건강 및 개인 도구",
        languageSectionTitle = "언어 및 다국어 설정",
        languageCardSubtitle = "동적 다국어 엔진 • 앱 전체에서 즉시 언어 전환",
        selectLanguageButton = "언어 변경",
        searchLanguagePlaceholder = "언어 또는 국가 검색...",
        themeSectionTitle = "시스템 테마 및 화면 설정",
        darkModeTitle = "시스템 다크 모드",
        darkModeActiveSubtitle = "Tailwind Slate-900 활성화 • OLED 고대비",
        lightModeActiveSubtitle = "Tailwind 라이트 활성화 • 선명하고 편안한 테마",
        themeLight = "☀️ 라이트",
        themeDark = "🌙 다크 (Slate)",
        themeAuto = "⚙️ 자동",
        calendarSyncTitle = "기기 캘린더 알림 동기화",
        calendarSyncActiveSubtitle = "활성화됨: DayMeet 알림이 로컬 캘린더에 연동됩니다",
        calendarSyncDisabledSubtitle = "비활성화됨: 앱 내 알림으로만 울립니다",

        coreIntelligenceHeader = "핵심 인텔리전스 엔진",
        automationsTitle = "자동화 규칙 엔진",
        automationsSubtitle = "언제 → 조건 → 실행 자동화 일일 워크플로우",
        aiCopilotTitle = "DayMeet AI 코파일럿",
        aiCopilotSubtitle = "자연어 기반 일정 재구성 및 인사이트",
        dailyBriefingTitle = "아침 및 저녁 브리핑",
        dailyBriefingSubtitle = "오늘의 주요 일정과 건강 지표 요약",

        productivityWorkspacesHeader = "생산성 및 워크스페이스",
        meetingsTitle = "미팅 및 화상 회의",
        meetingsSubtitle = "Google Meet, Zoom, Teams 연동",
        meetingMinutesTitle = "회의록 및 실행 항목",
        meetingMinutesSubtitle = "핵심 대화 내용을 할 일로 즉시 변환",
        pomodoroSanctuaryTitle = "뽀모도로 몰입 공간",
        pomodoroSanctuarySubtitle = "집중 음향과 방해 금지 모드",
        notesTitle = "노트, 문서 및 지식 보관소",
        notesSubtitle = "빠른 메모, 음성 녹음 및 태그 관리",

        habitsGoalsWellnessHeader = "습관, 목표 및 웰니스",
        habitsTitle = "습관 및 루틴 연속 기록",
        habitsSubtitle = "매일의 습관과 아침 루틴 트래킹",
        goalsTitle = "목표 및 마일스톤",
        goalsSubtitle = "재정, 운동 및 커리어 목표 추적",
        remindersTitle = "스마트 리마인더",
        remindersSubtitle = "위치, 시간 및 모듈 연계 알림",

        financeBillsCommerceHeader = "재정, 청구서 및 소비",
        financeDashboardTitle = "재정 대시보드 및 가계부",
        financeDashboardSubtitle = "일일 지출, 월간 예산 및 자동 분류",
        subscriptionsTitle = "구독 및 정기 결제",
        subscriptionsSubtitle = "통신비, 스트리밍, 소프트웨어 결제 관리",
        shoppingListsTitle = "장보기 및 쇼핑 리스트",
        shoppingListsSubtitle = "예산 예측과 품목별 체크리스트",

        travelSecurityHeader = "여행, 보안 및 연락처",
        travelItineraryTitle = "여행 일정 및 출장",
        travelItinerarySubtitle = "항공편, 호텔 예약 및 짐 싸기 목록",
        secureVaultTitle = "보안 문서 보관함",
        secureVaultSubtitle = "여권, 계약서 등 로컬 암호화 저장",
        contactsTitle = "연락처 및 예약 메시지",
        contactsSubtitle = "인맥 디렉토리 및 기념일 자동 알림",

        financialHealthTitle = "재정 건강 상태",
        spendingVelocitySubtitle = "소비 지출 속도",
        budgetTargetLimitButton = "한도 설정",
        velocityDialTab = "지출 속도 다이얼",
        runwayLimitTab = "잔여 일수 및 한도",
        statusSafe = "안전",
        statusSustainable = "적정",
        statusCaution = "주의",
        statusDanger = "초과 위험",
        currentSpendOfLimit = "한도 대비",

        priorityHigh = "높음",
        priorityMedium = "보통",
        priorityLow = "낮음",
        autoSortByPriority = "우선순위로 자동 정렬",
        actionSave = "저장",
        actionCancel = "취소",
        actionClose = "닫기",
        actionDone = "완료",
        actionEdit = "수정",
        actionDelete = "삭제",
        today = "오늘",
        upcoming = "예정"
    )

    val tamil = AppStrings(
        navHome = "முகப்பு",
        navCalendar = "நாள்காட்டி",
        navTasks = "பணிகள்",
        navInsights = "நுண்ணறிவு",
        navMore = "மேலும்",
        navCreate = "உருவாக்கு",

        liveBioSync = "நேரலை பயோ-ஒத்திசைவு",
        syncedJustNow = "இப்போது ஒத்திசைக்கப்பட்டது",
        focusPill = "கவனம்",
        focusActivePill = "கவனம் ஆன்",
        searchPlaceholder = "பணிகள், நிகழ்வுகள், பில்களைத் தேடுங்கள்...",
        notificationsTooltip = "அனைத்து அமைப்புகளும் ஒத்திசைக்கப்பட்டன: நாள்காட்டி, ஆரோக்கியம், பணிகள் & பட்ஜெட்",
        notificationsMutedTooltip = "🤫 அறிவிப்புகள் ஒலியடக்கப்பட்டுள்ளன: கவனம் பயன்முறையில் 12 அறிவிப்புகள் முடக்கப்பட்டன",
        aiCopilotTooltip = "DayMeet AI உதவியாளர்",

        focusModeHeader = "கவனம் பயன்முறை செயலில் உள்ளது",
        mutedBadge = "ஒலியடக்கம்",
        mutedSubtitle = "12 அவசரமற்ற அறிவிப்புகள் முடக்கப்பட்டன (Slack, மின்னஞ்சல்)",
        exitFocusButton = "வெளியேறு",
        activeFocusTaskQueue = "செயலில் உள்ள பணிகளின் வரிசை",
        subtasksChecklist = "துணைப்பணிகள் சரிபார்ப்பு பட்டியல்",
        markTaskComplete = "பணியை முடித்ததாகக் குறிக்கவும்",
        pomodoroFocusTitle = "ஆழ்ந்த கவன பொமோடோரோ",
        timerStart = "தொடங்கு",
        timerPause = "இடைநிறுத்து",
        focusSanctuaryClearTitle = "அனைத்து பணிகளும் முடிந்தது!",
        focusSanctuaryClearSubtitle = "வரிசையில் உள்ள அனைத்து பணிகளையும் முடித்துவிட்டீர்கள். சிறிது நேரம் ஓய்வெடுங்கள்.",

        commandCenterTitle = "கட்டளை மையம்",
        commandCenterSubtitle = "அனைத்து தொகுதிகள், ஆட்டோமேஷன், நிதி, ஆரோக்கியம் மற்றும் கருவிகள்",
        languageSectionTitle = "மொழி மற்றும் உள்ளூர்மயமாக்கல்",
        languageCardSubtitle = "இயக்கவியல் பன்மொழி அமைப்பு • ஆப் முழுவதும் உடனடி மொழி மாற்றம்",
        selectLanguageButton = "மொழியை மாற்றவும்",
        searchLanguagePlaceholder = "மொழி அல்லது நாட்டைத் தேடுங்கள்...",
        themeSectionTitle = "அமைப்பு தோற்றம் மற்றும் தீம்",
        darkModeTitle = "இருண்ட பயன்முறை",
        darkModeActiveSubtitle = "Tailwind Slate-900 செயலில் உள்ளது • உயர் மாறுபாடு",
        lightModeActiveSubtitle = "Tailwind வெளிர் பயன்முறை செயலில் உள்ளது",
        themeLight = "☀️ வெளிர்",
        themeDark = "🌙 இருண்ட (Slate)",
        themeAuto = "⚙️ தானியங்கி",
        calendarSyncTitle = "சாதன நாள்காட்டி அறிவிப்புகளை ஒத்திசைக்கவும்",
        calendarSyncActiveSubtitle = "செயலில்: DayMeet எச்சரிக்கைகள் உள்ளூர் நாள்காட்டியில் பிரதிபலிக்கும்",
        calendarSyncDisabledSubtitle = "முடக்கப்பட்டது: ஆப் உள் அறிவிப்புகள் மட்டுமே ஒலிக்கும்",

        coreIntelligenceHeader = "முக்கிய நுண்ணறிவு மற்றும் இயந்திரங்கள்",
        automationsTitle = "ஆட்டோமேஷன் மற்றும் விதிகள்",
        automationsSubtitle = "எப்போது → எனில் → பிறகு தானியங்கி தினசரி பணிப்பாய்வு",
        aiCopilotTitle = "DayMeet AI உதவியாளர்",
        aiCopilotSubtitle = "இயற்கை மொழியில் அட்டவணை மறுசீரமைப்பு மற்றும் நுண்ணறிவு",
        dailyBriefingTitle = "காலை மற்றும் மாலை விளக்கம்",
        dailyBriefingSubtitle = "இன்றைய பணிகள் மற்றும் ஆரோக்கியக் குறிப்புகள்",

        productivityWorkspacesHeader = "உற்பத்தித்திறன் மற்றும் பணியிடங்கள்",
        meetingsTitle = "கூட்டங்கள் மற்றும் வீடியோ சந்திப்புகள்",
        meetingsSubtitle = "Google Meet, Zoom, Teams ஒத்திசைவு",
        meetingMinutesTitle = "கூட்டக் குறிப்புகள் மற்றும் நடவடிக்கைகள்",
        meetingMinutesSubtitle = "முக்கிய குறிப்புகளை பணிகளாக மாற்றவும்",
        pomodoroSanctuaryTitle = "பொமோடோரோ கவன மையம்",
        pomodoroSanctuarySubtitle = "அமைதியான சூழலுடன் தொந்தரவு செய்யாத பயன்முறை",
        notesTitle = "குறிப்புகள், ஆவணங்கள் மற்றும் அறிவுத்தளம்",
        notesSubtitle = "விரைவான குறிப்புகள், குரல் குறிப்புகள் மற்றும் குறிச்சொற்கள்",

        habitsGoalsWellnessHeader = "பழக்கங்கள், இலக்குகள் மற்றும் ஆரோக்கியம்",
        habitsTitle = "பழக்கங்கள் மற்றும் தொடர் சாதனைகள்",
        habitsSubtitle = "தினசரி பழக்கவழக்கங்கள் மற்றும் காலை நடைமுறைகளைக் கண்காணிக்கவும்",
        goalsTitle = "இலக்குகள் மற்றும் மைல்கற்கள்",
        goalsSubtitle = "நிதி, உடற்பயிற்சி மற்றும் தொழில் இலக்குகளைக் கண்காணிக்கவும்",
        remindersTitle = "ஸ்மார்ட் நினைவூட்டல்கள்",
        remindersSubtitle = "இருப்பிடம், நேரம் மற்றும் தொகுதி அடிப்படையிலான எச்சரிக்கைகள்",

        financeBillsCommerceHeader = "நிதி, பில்கள் மற்றும் வணிகம்",
        financeDashboardTitle = "நிதி டாஷ்போர்டு மற்றும் பேரேடு",
        financeDashboardSubtitle = "தினசரி செலவு, மாதாந்திர பட்ஜெட் மற்றும் வகைப்பாடு",
        subscriptionsTitle = "சந்தாக்கள் மற்றும் தொடர் கட்டணங்கள்",
        subscriptionsSubtitle = "மின்சாரம், இணையம், ஸ்ட்ரீமிங் கட்டண கண்காணிப்பு",
        shoppingListsTitle = "ஷாப்பிங் மற்றும் மளிகைப் பட்டியல்கள்",
        shoppingListsSubtitle = "தானியங்கி பட்ஜெட் மதிப்பீடு",

        travelSecurityHeader = "பயணம், பாதுகாப்பு மற்றும் தொடர்புகள்",
        travelItineraryTitle = "பயணத் திட்டம் மற்றும் பயணங்கள்",
        travelItinerarySubtitle = "விமானங்கள், ஹோட்டல்கள் மற்றும் பேக்கிங் பட்டியல்",
        secureVaultTitle = "பாதுகாப்பான ஆவண பெட்டகம்",
        secureVaultSubtitle = "பாஸ்போர்ட், ஒப்பந்தங்கள் குறியாக்கம் செய்யப்பட்டு சேமிக்கப்படும்",
        contactsTitle = "தொடர்புகள் மற்றும் திட்டமிடப்பட்ட செய்திகள்",
        contactsSubtitle = "தொடர்பு அடைவு மற்றும் பிறந்தநாள் வாழ்த்துக்கள்",

        financialHealthTitle = "நிதி ஆரோக்கியம்",
        spendingVelocitySubtitle = "செலவு வேகம்",
        budgetTargetLimitButton = "வரம்பு",
        velocityDialTab = "வேக டயல்",
        runwayLimitTab = "எஞ்சிய நாட்களும் வரம்பும்",
        statusSafe = "பாதுகாப்பானது",
        statusSustainable = "நிலையானது",
        statusCaution = "எச்சரிக்கை",
        statusDanger = "ஆபத்து",
        currentSpendOfLimit = "வரம்பில்",

        priorityHigh = "உயர்",
        priorityMedium = "நடுத்தர",
        priorityLow = "குறைந்த",
        autoSortByPriority = "முன்னுரிமை அடிப்படையில் வரிசைப்படுத்து",
        actionSave = "சேமிக்க",
        actionCancel = "ரத்துசெய்",
        actionClose = "மூடு",
        actionDone = "முடிந்தது",
        actionEdit = "திருத்து",
        actionDelete = "நீக்கு",
        today = "இன்று",
        upcoming = "வரவிருக்கும்"
    )
}
